name: Spring CI/CD

# 트리거
on:
  push:
    branches:
      - test

# 해야 될 일
jobs:
  cicd-deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub Repository 파일 체크아웃
      - name: Github Repository내 파일들 checkout 수행
        uses: actions/checkout@v4

      # JDK 17 설치
      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # application.yml 동적 생성
      - name: application.properties 동적 생성
        run: |
          echo "${{ secrets.APPLICATION_TEST }}" > ./src/main/resources/application.yml
          ls ./src/main/resources/application.yml

      # 빌드 수행
      - name: 단위 테스트 및 빌드
        run: |
          if [ ! -x ./gradlew ]; then chmod +x ./gradlew; fi
          ./gradlew clean build
          ls ./build/libs

      # 빌드 결과물 이름 변경
      - name: 관리상 빌드된 결과물의 이름을 변경 처리
        run: |
          mv ./build/libs/*SNAPSHOT.jar ./run.jar
          ls
      
      

      # EC2로 빌드된 JAR 파일 업로드
      - name: EC2에 jar파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: run.jar
          target: /home/ubuntu/server/demo

      # EC2에서 기존 서버 정리 및 애플리케이션 실행
      - name: SSH로 ec2에 정리 후, 접속 후 서버 가동
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/server/popup
            mkdir /home/ubuntu/server/popup
            mv /home/ubuntu/server/demo/run.jar /home/ubuntu/server/popup/run.jar
            cd /home/ubuntu/server/popup
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar run.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/server/demo